---
title: "Week06_Assignment"
author: "Ally Malilay"
format: html
---

## Introduction
Let's take a closer look at the *Chemical Data* from *Mauna Lua*!

# Load libraries and data

```{r}
#load libraries
#| message: false

library(tidyverse)
library(here)
library(kableExtra)

## Load data ######
ChemData <- read_csv(here("Week_06", "Data", "chemicaldata_maunalua.csv"))
```

## Data analysis
In different seasons and tides, what is the difference between average values for salinity, phosphate, and silicate? 

```{r}
ChemData_clean <- ChemData %>% #pipe in dataset to clean
  drop_na() %>% #drop all NAs
  separate(col = Tide_time, #choose tide_time column
           into = c("Tide", "Time"), 
           sep = "_", #separate by _
           remove = FALSE) %>% #keep Tide_Time column 
  pivot_longer(cols = Temp_in:percent_sgd, #choose columns to pivot 
               names_to = "Variables", 
               values_to = "Values") %>% #name of new column holding variable values
  group_by(`Variables`, Tide, Season) %>% #group by everything we want
  summarise(Param_means = mean(Values, na.rm = TRUE))
```

## Make a plot
```{r}
ggplot(ChemData_clean, aes(x= Season, y = Values)) +
  geom_crossbar() 
```

