---
title: "Tidy Tuesday Assignment 1"
format: html
toc: true
author: "Ally Malilay"
date: "2025-11-11"
theme: united
mainfont: "Arial, sans-serif"
---

# Load our libraries & data
```{r}
#Libraries
library(tidytuesdayR)
library(ggplot2)
library(tidyr)
library(dplyr)
library(here)
#Load data
tuesdata <- tidytuesdayR::tt_load(2025, week = 44)
flint_mdeq <- tuesdata$flint_mdeq
flint_vt <- tuesdata$flint_vt
```

# Tidy up the data
```{r}
mdeq_long <- flint_mdeq %>% 
  select(sample, lead) %>% #use column with sample removed due to filter presence/business status
  pivot_longer(cols = lead, #pivot mdeq to long
                 names_to = "data", #name of new column
               values_to = "lead") %>%
  mutate(data = ifelse(data == "lead", "MDEQ", data))

vt_cleaned <- flint_vt %>% #clean vt data to combine two datasets
  mutate(data = "VT") #new column named data with VT as value

flintdata <- bind_rows(mdeq_long, vt_cleaned) #combine datasets
```

# Plot
This is my first time plotting using a histogram! Woohoo to learning new things.
```{r}
flintvtplot <- ggplot(flintdata, aes(x = lead)) + 
  geom_histogram(binwidth = 6, color = "black") + #add geometry
  labs(title = "Distribution of lead levels in Flint, MI", #titles for axes
       caption = "Data: Michigan Department of Environment (MDEQ) and Virginia Tech (VT) citizen science project",
       x = "Lead concentration (ppb)",
       y = "Frequency (count)") +
  facet_wrap(~data) #separate plots by research project

flintvtplot
ggsave(here("Tidy_Tuesday","2025-11-04","Output","LeadLevelsDistribution.png"))
```

