---
title: "Tidy Tuesday 5"
format: html
runtime: shiny
output: html_document
toc: true
author: "Ally Malilay"
date: "2025-12-8"
theme: united
mainfont: "Arial, sans-serif"
---
 
# Load libraries and our data!
```{r}
#| message: false
#| warning: false

#Load libraries
library(tidytuesdayR)
library(tidyverse)
library(shiny)

sechselaeuten <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-12-02/sechselaeuten.csv')
```

# Make a plot
```{r echo = FALSE}
# Select type of trend to plot
selectInput("n_breaks", label = "Number of bins:",
              choices = c(10, 20, 35, 50), selected = 20)

sliderInput("bw_adjust", label = "Bandwidth adjustment:",
              min = 0.2, max = 2, value = 1, step = 0.2)

```

# Make them reactive
```{r echo = FALSE}
#| context: server
renderPlot({
  hist(faithful$eruptions, probability = TRUE,
       breaks = as.numeric(input$n_breaks),
       xlab = "Duration (minutes)",
       main = "Geyser eruption duration")

  dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  lines(dens, col = "blue")
})
```

